In [8]:
import numpy as np
arr = np.array([[[1,2],[3,4]],[[4,6],[9,8]]])
arr

array([[[1, 2],
        [3, 4]],

       [[4, 6],
        [9, 8]]])

In [9]:
arr.shape

(2, 2, 2)

In [10]:
arr.ndim


3

In [12]:
import sys
lists = range(100)
arr = np.arange(100)

print(sys.getsizeof(8)*len(lists))

2800


In [15]:
import time
x = range(100000)
y = range(100000, 200000)

starttime = time.time()
c  = [(x,y) for x,y in zip(x,y)]

print(time.time() - starttime)


0.03842473030090332


In [19]:
y = np.arange(100000)
b = np.arange(100000, 200000)
starttime = time.time()
c  = y + b

print(time.time() - starttime)


0.018945932388305664


In [20]:
#indexinf slicing iterations
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
arr = arr.reshape(6,4)

In [27]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [32]:
arr[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [34]:
arr[2:4
    , 1:3]

array([[ 9, 10],
       [13, 14]])

In [35]:
#iteration

for i in arr:
    print(i)


[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [36]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [37]:
ar = np.array([1,2,3,4,5,6,7])
ar

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
ar > 3

array([False, False, False,  True,  True,  True,  True])

In [39]:
arr.sum(axis = 0)

array([60, 66, 72, 78])

In [41]:
np.where(arr % 2 == 1, -1, arr)

array([[ 0, -1,  2, -1],
       [ 4, -1,  6, -1],
       [ 8, -1, 10, -1],
       [12, -1, 14, -1],
       [16, -1, 18, -1],
       [20, -1, 22, -1]])

In [42]:
np.where(ar % 2 == 1, -1, ar)

array([-1,  2, -1,  4, -1,  6, -1])

In [43]:
ar


array([1, 2, 3, 4, 5, 6, 7])

In [45]:
ar[ar % 2 == 1] = -1

In [46]:
ar

array([-1,  2, -1,  4, -1,  6, -1])